version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: some-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3307:3306"
    networks:
      - prestashop-net

  prestashop:
    image: prestashop/prestashop
    container_name: some-prestashop
    environment:
      DB_SERVER: some-mysql
    ports:
      - "10.0.9.21"
    networks:
      - prestashop-net

networks:
  prestashop-net: